title: Ibukun Olusunmade Data Analytics Projects
#logo: /assets/img/logo.png
description: I am passionate about using data to solve real-world problems, particularly in different sectors such as healthcare, business environments and many more. My goal is to leverage data-driven insights to support decision-making and improve outcomes..
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
